import { Baby, Film, Flame, Flower, IceCream, Leaf, Moon, Mountain, Palmtree, Rose, Snowflake, Sun } from "lucide-react";

export const bundles = [
    {
        id: "cinetone-pro-all-in-one",
        slug: "cinetone-pro-all-in-one",
        title: "Cinetone Pro All In One",
        description: "This is a featured bundle",
        image: "/bundles/cinetone-pro-all-in-one.png",
        org_price: 199,
        price: 149,
        type: "bundle",
        tags: ["Cinetone Pro", "All In One"],
    },
    {
        id: "master-collection",
        slug: "master-collection",
        title: "Master Collection",
        description: "This is a featured bundle",
        image: "/bundles/master-collection.jpg",
        org_price: 199,
        price: 149,
        type: "bundle",
        tags: ["Master Collection"],
    },
    {
        id: "master-collection-1",
        slug: "master-collection-1",
        title: "Master Collection 1",
        description: "This is a featured bundle",
        image: "/bundles/master-collection.jpg",
        org_price: 199,
        price: 149,
        type: "bundle",
        tags: ["Master Collection", "Featured"],
    },
    {
        id: "master-collection-2",
        slug: "master-collection-2",
        title: "Master Collection 2",
        description: "This is a featured bundle",
        image: "/bundles/master-collection.jpg",
        org_price: 199,
        price: 149,
        type: "bundle",
        tags: ["Master Collection", "Featured"],
    },
    {
        id: "master-collection-3",
        slug: "master-collection-3",
        title: "Master Collection 3",
        description: "This is a featured bundle",
        image: "/bundles/master-collection.jpg",
        org_price: 199,
        price: 149,
        type: "bundle",
        tags: [""],
    },
    {
        id: "master-collection-4",
        slug: "master-collection-4",
        title: "Master Collection 4",
        description: "This is a featured bundle",
        image: "/bundles/master-collection.jpg",
        org_price: 199,
        price: 149,
        type: "bundle",
        tags: [""],
    },
];

export const presets = [
    {
        id: "film-pro-collection-featured",
        slug: "film-pro-collection-featured",
        title: "Film Pro Collection Featured",
        description: "This is a featured preset",
        image: "/presets/film-pro-collection-featured.jpg",
        org_price: 199,
        price: 149,
        type: "preset",
        tags: ["Film Pro Collection Featured"],
    },
    {
        id: "film-pro-collection-featured-1",
        slug: "film-pro-collection-featured1",
        title: "Film Pro Collection Featured 1",
        description: "This is a featured preset",
        image: "/presets/film-pro-collection-featured.jpg",
        org_price: 199,
        price: 149,
        type: "preset",
        tags: ["Film Pro Collection Featured"],
    },
    {
        id: "film-pro-collection-featured-2",
        slug: "film-pro-collection-featured-2",
        title: "Film Pro Collection Featured 2",
        description: "This is a featured preset",
        image: "/presets/film-pro-collection-featured.jpg",
        org_price: 199,
        price: 149,
        type: "preset",
        tags: ["Film Pro Collection Featured"],
    },
    {
        id: "film-pro-collection-featured-3",
        slug: "film-pro-collection-featured-3",
        title: "Film Pro Collection Featured 3",
        description: "This is a featured preset",
        image: "/presets/film-pro-collection-featured.jpg",
        org_price: 199,
        price: 149,
        type: "preset",
        tags: ["Film Pro Collection Featured"],
    },
    {
        id: "film-pro-collection-featured-4",
        slug: "film-pro-collection-featured-4",
        title: "Film Pro Collection Featured 4",
        description: "This is a featured preset",
        image: "/presets/film-pro-collection-featured.jpg",
        org_price: 199,
        price: 149,
        type: "preset",
        tags: ["Film Pro Collection Featured"],
    },
    {
        id: "film-pro-collection-featured-5",
        slug: "film-pro-collection-featured-5",
        title: "Film Pro Collection Featured 5",
        description: "This is a featured preset",
        image: "/presets/film-pro-collection-featured.jpg",
        org_price: 199,
        price: 149,
        type: "preset",
        tags: ["Film Pro Collection Featured"],
    },
];

export const tones = [
    {
      id: "bright-and-airy",
      slug: "bright-and-airy",
      title: "Bright and Airy",
      description: "Perfect for sunny, outdoor scenes and vibrant cityscapes.",
      image: "/presets/bright-airy-gray.jpg",
      icon: Sun,
    },
    {
      id: "creamy-tones",
      slug: "creamy-tones",
      title: "Creamy Tones",
      description: "Ideal for warm, natural light and soft skin tones.",
      image: "/presets/creamy-tones.jpg",
      icon: IceCream,
    },
    {
      id: "warm-tones",
      slug: "warm-tones",
      title: "Warm Tones",
      description: "Ideal for warm, natural light and soft skin tones.",
      image: "/presets/earth-tones.jpg",
      icon: Flame,
    },
    {
      id: "dark-moody-tones",
      slug: "dark-moody-tones",
      title: "Dark & Moody Tones",
      description: "Ideal for dark, moody scenes and dramatic portraits.",
      image: "/presets/dark-moody-tone.jpg",
      icon: Moon,
    },
    {
      id: "cinematic-tones",
      slug: "cinematic-tones",
      title: "Cinematic Tones",
      description: "Ideal for cinematic scenes and dramatic portraits.",
      image: "/presets/cine-tones.jpg",
      icon: Film,
    },
  ];

export const seasons = [
    {
      id: "spring",
      slug: "spring",
      title: "Spring",
      description: "Ideal for spring photography.",
      image: "/presets/spring.jpg",
      icon: Flower,
    },
    {
      id: "summer",
      slug: "summer",
      title: "Summer",
      description: "Ideal for summer photography.",
      image: "/presets/summer.jpg",
      icon: Sun,
    },
    {
      id: "autumn",
      slug: "autumn",
      title: "Autumn",
      description: "Ideal for fall photography.",
      image: "/presets/autumn.jpg",
      icon: Leaf,
    },
    {
      id: "winter",
      slug: "winter",
      title: "Winter",
      description: "Ideal for winter photography.",
      image: "/presets/bright-winter.jpg",
      icon: Snowflake,
    },
  ];




export const scenes = [
    {
      id: "landscape",
      slug: "landscape",
      title: "Landscape",
      description: "Perfect for landscape photography.",
      image: "/presets/landscapes.jpg",
      icon: Mountain,
    },
    {
      id: "tropical",
      slug: "tropical",
      title: "Tropical",
      description: "Ideal for tropical photography.",
      image: "/presets/tropical.jpg",
      icon: Palmtree,
    },
    {
      id: "wedding",
      slug: "wedding",
      title: "Wedding",
      description: "Ideal for wedding photography.",
      image: "/presets/garden-wedding.jpg",
      icon: Rose,
    },
    {
      id: "family",
      slug: "family",
      title: "Family",
      description: "Ideal for family photography.",
      image: "/presets/cozy-home.jpg",
      icon: Baby,
    },
  ];

  export const navitems = {
    tones,
    seasons,
    scenes,
  };