import type { Metadata } from "next";
import { Cormorant, Quicksand } from "next/font/google";
import Navbar from "@/components/header/navBar";
import Footer from "@/components/home/footer";
import "./globals.css";
const cormorant = Cormorant({
  variable: "--font-cormorant",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cormorant.variable} ${quicksand.variable} font-mono antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
